# Generated by Django 5.0.3 on 2024-09-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='types',
            field=models.CharField(choices=[('Nha', 'Tiền nhà'), ('Dien', 'Tiền điện'), ('Dich vu', 'Tiền phí dịch vụ')], default='Nha', max_length=50, null=True),
        ),
    ]
